@startuml

:Admin: as A
:User: as U

(User service) as US
(Application service) as AS
(user DB) as UDB
(application DB) as ADB
(Analytics API) as AA
(Device service) as DS
(Kafka) as K
(Analytics Consumer) as AC
(analytics DB) as ANDB


A <--> US
US --> UDB
A --> AS
AS --> ADB
A --> AA
U <--> US
U --> DS
DS --> K
K --> AC
AC --> ANDB
ANDB --> AA

@enduml
