@startuml

actor "User"

"User" -> "User service": Sign up
"User service" -> "User": Api token
"User service" -> "User DB": Save user to DB
"User" -> "Device service": Api token
"Device service" -> "Kafka": produce to Kafka
"Kafka" -> "Analytics consumer": consume from Kafka
"Analytics consumer" -> "Analytics DB": save statistics to DB

@enduml
