@startuml

actor "Admin"

"Admin"-> "User service": save new client
"User service"-> "User DB": save new user
"Admin"<- "User service": jwt-token
"Admin"-> "Application service": create app
"Application service"-> "Application DB": create app
"Admin" -> "Analytics API": /<app_uuid> with jwt-token
"Analytics API" -> "Admin": statistics
"Analytics API" <- "Analytics DB": return statistics
"Analytics API" -> "Analytics DB": select statistics
"Analytics DB" <- "Analytics consumer": save statistics to DB
"Analytics consumer" <- "Kafka": consume from Kafka
"Kafka" <- "Device service": produce to Kafka

@enduml
